### ISSUE TITLE
Exporting GPIO pins

### ISSUE THREAD

**Issue by jurafa** [nebrius/raspi-pwm#1] opened 2015-04-22 13:15 UTC
Hi.
I had to export the GPIO pin and set pwm mode before this module started to work. 

echo 18 > /sys/class/gpio/export 
gpio mode 1 pwm

In my opinion this should be handled by the library or it should be mentioned in README.

**Comment by nebrius** [comment] 2015-04-22 16:24
Hmmm, that's not a requirement for the library and something I've never had to do. I wonder why it's necessary for you?

Can you give us the following information so we can try and figure out what's going on?
- Raspberry Pi model, e.g. "Raspberry Pi 2 Model B"
- OS and version, e.g. "Raspbian  2015-02-16"
- Node version, `node -v`
- Installed modules, `npm list` (this one will be long)
- Wiring Pi version, `gpio -v`

**Comment by jurafa** [comment] 2015-04-23 10:16
My specs:
Raspberry Pi Details:
Type: Model B+, Revision: 1.2, Memory: 512MB, Maker: Sony
Wiring Pi  version: 2.20
node -v - v0.10.25

npm list (I am testing more staff right now...)
/home/user/test
├─┬ mcp3424@0.0.1
│ ├── coffee-script@1.3.3
│ └─┬ i2c@0.1.4
│   ├── bindings@1.1.1
│   ├── repl@0.1.3
│   └── underscore@1.2.4
├─┬ raspi@1.3.0
│ ├── nan@1.6.2
│ └── raspi-wiringpi@1.0.4
├─┬ raspi-pwm@1.3.1
│ ├── nan@1.6.2
│ └─┬ raspi-peripheral@1.1.1
│   └── raspi-board@2.1.1
├─┬ rpi-gpio@0.5.1
│ ├── async@0.8.0
│ └── debug@0.8.1
└─┬ rpio@0.4.3
  ├── addon-layer@0.0.1 (git://github.com/tjfontaine/node-addon-layer.git#b4b67d11ed54ae6dec0c3a1e653c6be5042088c6)
  └── bindings@1.2.1

kernel:
uname -a
Linux raspberrypi 3.18.5+ #744 PREEMPT Fri Jan 30 18:19:07 GMT 2015 armv6l GNU/Linux

**Comment by nebrius** [comment] 2015-04-23 16:56
Can you try a few things for me?
- Upgrade Node.js to the latest version, either 0.10.38, 0.12.2, or iojs 1.8.1
- Upgrade Wiring Pi to the latest version, I have 2.26. You may have to do this manually.
- Install the latest version of Raspbian (I have kernel 3.18.7). I know that a few things were changed around initialization of peripherals pretty recently, so make sure you're using Raspbian 2015-02-16
- Remove any and all uses of rpio in your code. It may be causing a conflict

Also, can you post a minimum viable example code that reproduces the issue for you?

**Comment by nebrius** [comment] 2015-05-04 05:21
@jurafa if you're able to narrow down what caused the issue, I'd love to hear it. In the mean time though, I'm going to go ahead and close this issue since I believe it is being caused by an outdated version of Raspbian.

**Closed as completed by nebrius** 2015-05-04 05:21 UTC
